"""initial schema

Revision ID: 631222db9971
Revises: 
Create Date: 2026-08-27 11:08:01.238617
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401  (referenced by autogenerated JSONB variants)
from sqlalchemy.dialects import postgresql  # noqa: F401

import app.db.types  # noqa: F401  (referenced by autogenerated UTCDateTime columns)

revision: str = '631222db9971'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city_external_id', sa.String(length=64), nullable=True),
    sa.Column('country_external_id', sa.String(length=64), nullable=True),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('media', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('popularity_rank', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('last_seen_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'external_id', name='uq_attractions_market_ext')
    )
    with op.batch_alter_table('attractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attractions_market'), ['market'], unique=False)
        batch_op.create_index('ix_attractions_market_city', ['market', 'city_external_id'], unique=False)

    op.create_table('budget_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spend_date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('released_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_reservations_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_reservations_spend_date'), ['spend_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_reservations_status'), ['status'], unique=False)

    op.create_table('catalog_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_external_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('fetched_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_snapshots_entity_external_id'), ['entity_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_snapshots_market'), ['market'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('last_seen_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'external_id', name='uq_categories_market_ext')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_market'), ['market'], unique=False)

    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_external_id', sa.String(length=64), nullable=True),
    sa.Column('country_name', sa.String(length=255), nullable=True),
    sa.Column('popular', sa.Boolean(), nullable=False),
    sa.Column('media', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('attraction_count', sa.Integer(), nullable=False),
    sa.Column('popularity_rank', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('last_seen_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'external_id', name='uq_cities_market_ext')
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cities_country_external_id'), ['country_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cities_market'), ['market'], unique=False)
        batch_op.create_index('ix_cities_market_product_count', ['market', 'product_count'], unique=False)

    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('last_seen_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'external_id', name='uq_collections_market_ext')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_market'), ['market'], unique=False)

    op.create_table('conversion_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_order_id', sa.String(length=128), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('product_external_id', sa.String(length=64), nullable=True),
    sa.Column('gmv', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('currency_code', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_order_id', name='uq_conversion_order')
    )
    with op.batch_alter_table('conversion_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversion_events_article_id'), ['article_id'], unique=False)

    op.create_table('cost_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spend_date', sa.Date(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('llm_run_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('task', sa.String(length=48), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_ledger_article_id'), ['article_id'], unique=False)
        batch_op.create_index('ix_cost_ledger_day_market', ['spend_date', 'market'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_ledger_spend_date'), ['spend_date'], unique=False)

    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('media', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('city_count', sa.Integer(), nullable=False),
    sa.Column('popularity_rank', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('last_seen_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'external_id', name='uq_countries_market_ext')
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_market'), ['market'], unique=False)

    op.create_table('keyword_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('primary_pattern', sa.Text(), nullable=False),
    sa.Column('secondary_patterns', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('min_inventory', sa.Integer(), nullable=False),
    sa.Column('requires_volatile_facts', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'entity_type', 'intent', name='uq_keyword_cluster')
    )
    with op.batch_alter_table('keyword_clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keyword_clusters_market'), ['market'], unique=False)

    op.create_table('llm_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(length=8), nullable=True),
    sa.Column('task', sa.String(length=48), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('web_search_calls', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_runs_article_id'), ['article_id'], unique=False)
        batch_op.create_index('ix_llm_runs_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_runs_job_id'), ['job_id'], unique=False)

    op.create_table('markets',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('store_domain', sa.String(length=128), nullable=False),
    sa.Column('currency_code', sa.String(length=8), nullable=False),
    sa.Column('telegram_channel', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('highlights', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('cover', sa.Text(), nullable=True),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('audio_preview_url', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('exprice', sa.Float(), nullable=True),
    sa.Column('currency_code', sa.String(length=8), nullable=True),
    sa.Column('currency_symbol', sa.String(length=8), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('ratings_count', sa.Integer(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('duration_max', sa.Integer(), nullable=True),
    sa.Column('duration_text', sa.String(length=128), nullable=True),
    sa.Column('distance', sa.String(length=64), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('types', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('inclusions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('exclusions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('important_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('start_location', sa.Text(), nullable=True),
    sa.Column('location_geo', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('country_external_id', sa.String(length=64), nullable=True),
    sa.Column('city_external_id', sa.String(length=64), nullable=True),
    sa.Column('primary_category', sa.String(length=255), nullable=True),
    sa.Column('reviews', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('popularity_rank', sa.Integer(), nullable=True),
    sa.Column('detail_fetched_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('api_updated_at', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'external_id', name='uq_products_market_ext')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_country_external_id'), ['country_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_market'), ['market'], unique=False)
        batch_op.create_index('ix_products_market_available', ['market', 'available'], unique=False)
        batch_op.create_index('ix_products_market_city', ['market', 'city_external_id'], unique=False)

    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=True),
    sa.Column('task', sa.String(length=48), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_prompt_version')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_versions_name'), ['name'], unique=False)

    op.create_table('query_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('canonical_query', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_external_id', sa.String(length=64), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('demand_score', sa.Float(), nullable=True),
    sa.Column('demand_source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'canonical_query', name='uq_query_candidate_canonical')
    )
    with op.batch_alter_table('query_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_candidates_market'), ['market'], unique=False)

    op.create_table('search_demand_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('trend', sa.Float(), nullable=True),
    sa.Column('competition', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('captured_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_demand_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_demand_snapshots_market'), ['market'], unique=False)

    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_runs_job_id'), ['job_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('topic_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('topic_key', sa.String(length=255), nullable=False),
    sa.Column('topic_slug', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_external_id', sa.String(length=64), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('primary_query', sa.Text(), nullable=False),
    sa.Column('canonical_query', sa.Text(), nullable=False),
    sa.Column('secondary_queries', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('relevant_product_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('inventory_depth', sa.Integer(), nullable=False),
    sa.Column('topic_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('demand_confidence', sa.Float(), nullable=False),
    sa.Column('demand_source', sa.String(length=32), nullable=False),
    sa.Column('requires_volatile_facts', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('boost', sa.Float(), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('last_used_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'topic_key', name='uq_topic_candidate_key')
    )
    with op.batch_alter_table('topic_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_candidates_market'), ['market'], unique=False)
        batch_op.create_index('ix_topic_candidates_market_status_score', ['market', 'status', 'topic_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_candidates_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_candidates_topic_score'), ['topic_score'], unique=False)

    op.create_table('verified_fact_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('fact_key', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('source_tier', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verified_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'fact_key', name='uq_verified_fact_key')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('topic_slug', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_external_id', sa.String(length=64), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('primary_query', sa.Text(), nullable=False),
    sa.Column('secondary_queries', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('body', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('rendered_message', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('quality_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('factuality_score', sa.Float(), nullable=True),
    sa.Column('validation_issues', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('actual_cost_usd', sa.Float(), nullable=False),
    sa.Column('generation_attempts', sa.Integer(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('published_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('approved_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('products_refreshed_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_candidates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_market'), ['market'], unique=False)
        batch_op.create_index('ix_articles_market_status', ['market', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_articles_status'), ['status'], unique=False)
        batch_op.create_index('ix_articles_status_scheduled', ['status', 'scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_topic_id'), ['topic_id'], unique=False)

    op.create_table('product_attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('attraction_external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'attraction_external_id', name='uq_product_attraction')
    )
    with op.batch_alter_table('product_attractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_attractions_attraction_external_id'), ['attraction_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_attractions_product_id'), ['product_id'], unique=False)

    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_external_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'category_external_id', name='uq_product_category')
    )
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_categories_category_external_id'), ['category_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_categories_product_id'), ['product_id'], unique=False)

    op.create_table('product_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('collection_external_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'collection_external_id', name='uq_product_collection')
    )
    with op.batch_alter_table('product_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_collections_collection_external_id'), ['collection_external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_collections_product_id'), ['product_id'], unique=False)

    op.create_table('product_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('preview_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_media_product_id'), ['product_id'], unique=False)

    op.create_table('article_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('requires_verification', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('source_tier', sa.Integer(), nullable=True),
    sa.Column('product_external_id', sa.String(length=64), nullable=True),
    sa.Column('api_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verified_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('checked_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_claims_article_id'), ['article_id'], unique=False)

    op.create_table('article_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_entity_type', sa.String(length=32), nullable=True),
    sa.Column('source_entity_id', sa.String(length=64), nullable=True),
    sa.Column('product_external_id', sa.String(length=64), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_media_article_id'), ['article_id'], unique=False)

    op.create_table('article_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('product_external_id', sa.String(length=64), nullable=False),
    sa.Column('placement', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('rank_score', sa.Float(), nullable=False),
    sa.Column('rank_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('affiliate_url', sa.Text(), nullable=True),
    sa.Column('tracking_url', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'product_external_id', name='uq_article_product')
    )
    with op.batch_alter_table('article_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_products_article_id'), ['article_id'], unique=False)

    op.create_table('article_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('accessed_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_sources_article_id'), ['article_id'], unique=False)

    op.create_table('article_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('rendered_message', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('quality_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'version', name='uq_article_version')
    )
    with op.batch_alter_table('article_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_versions_article_id'), ['article_id'], unique=False)

    op.create_table('publication_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('target', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scheduled_for', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('locked_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('article_version', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_publication_queue_idempotency')
    )
    with op.batch_alter_table('publication_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_queue_article_id'), ['article_id'], unique=False)
        batch_op.create_index('ix_publication_queue_status_time', ['status', 'scheduled_for'], unique=False)

    op.create_table('telegram_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('target', sa.String(length=16), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=True),
    sa.Column('channel_username', sa.String(length=128), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('message_url', sa.Text(), nullable=True),
    sa.Column('article_version', sa.Integer(), nullable=True),
    sa.Column('telegram_response', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('published_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('edited_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('edit_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_telegram_publication_idempotency')
    )
    with op.batch_alter_table('telegram_publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_publications_article_id'), ['article_id'], unique=False)

    op.create_table('tracking_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('link_type', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_external_id', sa.String(length=64), nullable=True),
    sa.Column('product_external_id', sa.String(length=64), nullable=True),
    sa.Column('placement', sa.String(length=32), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('unique_clicks', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracking_links', schema=None) as batch_op:
        batch_op.create_index('ix_tracking_links_article', ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracking_links_token'), ['token'], unique=True)

    op.create_table('click_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_link_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('visitor_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referer', sa.Text(), nullable=True),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tracking_link_id'], ['tracking_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('click_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_click_events_article_id'), ['article_id'], unique=False)
        batch_op.create_index('ix_click_events_link_time', ['tracking_link_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_events_visitor_hash'), ['visitor_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('click_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_click_events_visitor_hash'))
        batch_op.drop_index('ix_click_events_link_time')
        batch_op.drop_index(batch_op.f('ix_click_events_article_id'))

    op.drop_table('click_events')
    with op.batch_alter_table('tracking_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracking_links_token'))
        batch_op.drop_index('ix_tracking_links_article')

    op.drop_table('tracking_links')
    with op.batch_alter_table('telegram_publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_publications_article_id'))

    op.drop_table('telegram_publications')
    with op.batch_alter_table('publication_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_publication_queue_status_time')
        batch_op.drop_index(batch_op.f('ix_publication_queue_article_id'))

    op.drop_table('publication_queue')
    with op.batch_alter_table('article_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_versions_article_id'))

    op.drop_table('article_versions')
    with op.batch_alter_table('article_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_sources_article_id'))

    op.drop_table('article_sources')
    with op.batch_alter_table('article_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_products_article_id'))

    op.drop_table('article_products')
    with op.batch_alter_table('article_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_media_article_id'))

    op.drop_table('article_media')
    with op.batch_alter_table('article_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_claims_article_id'))

    op.drop_table('article_claims')
    with op.batch_alter_table('product_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_media_product_id'))

    op.drop_table('product_media')
    with op.batch_alter_table('product_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_collections_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_collections_collection_external_id'))

    op.drop_table('product_collections')
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_categories_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_categories_category_external_id'))

    op.drop_table('product_categories')
    with op.batch_alter_table('product_attractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_attractions_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_attractions_attraction_external_id'))

    op.drop_table('product_attractions')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_topic_id'))
        batch_op.drop_index('ix_articles_status_scheduled')
        batch_op.drop_index(batch_op.f('ix_articles_status'))
        batch_op.drop_index(batch_op.f('ix_articles_public_id'))
        batch_op.drop_index('ix_articles_market_status')
        batch_op.drop_index(batch_op.f('ix_articles_market'))

    op.drop_table('articles')
    op.drop_table('verified_fact_cache')
    with op.batch_alter_table('topic_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_candidates_topic_score'))
        batch_op.drop_index(batch_op.f('ix_topic_candidates_status'))
        batch_op.drop_index('ix_topic_candidates_market_status_score')
        batch_op.drop_index(batch_op.f('ix_topic_candidates_market'))

    op.drop_table('topic_candidates')
    op.drop_table('system_settings')
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_runs_job_id'))

    op.drop_table('sync_runs')
    with op.batch_alter_table('search_demand_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_demand_snapshots_market'))

    op.drop_table('search_demand_snapshots')
    with op.batch_alter_table('query_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_candidates_market'))

    op.drop_table('query_candidates')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_versions_name'))

    op.drop_table('prompt_versions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_market_city')
        batch_op.drop_index('ix_products_market_available')
        batch_op.drop_index(batch_op.f('ix_products_market'))
        batch_op.drop_index(batch_op.f('ix_products_country_external_id'))

    op.drop_table('products')
    op.drop_table('markets')
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_runs_job_id'))
        batch_op.drop_index('ix_llm_runs_created')
        batch_op.drop_index(batch_op.f('ix_llm_runs_article_id'))

    op.drop_table('llm_runs')
    with op.batch_alter_table('keyword_clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_clusters_market'))

    op.drop_table('keyword_clusters')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_market'))

    op.drop_table('countries')
    with op.batch_alter_table('cost_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_ledger_spend_date'))
        batch_op.drop_index('ix_cost_ledger_day_market')
        batch_op.drop_index(batch_op.f('ix_cost_ledger_article_id'))

    op.drop_table('cost_ledger')
    with op.batch_alter_table('conversion_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversion_events_article_id'))

    op.drop_table('conversion_events')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_market'))

    op.drop_table('collections')
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index('ix_cities_market_product_count')
        batch_op.drop_index(batch_op.f('ix_cities_market'))
        batch_op.drop_index(batch_op.f('ix_cities_country_external_id'))

    op.drop_table('cities')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_market'))

    op.drop_table('categories')
    with op.batch_alter_table('catalog_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_snapshots_market'))
        batch_op.drop_index(batch_op.f('ix_catalog_snapshots_entity_external_id'))

    op.drop_table('catalog_snapshots')
    with op.batch_alter_table('budget_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_reservations_status'))
        batch_op.drop_index(batch_op.f('ix_budget_reservations_spend_date'))
        batch_op.drop_index(batch_op.f('ix_budget_reservations_article_id'))

    op.drop_table('budget_reservations')
    with op.batch_alter_table('attractions', schema=None) as batch_op:
        batch_op.drop_index('ix_attractions_market_city')
        batch_op.drop_index(batch_op.f('ix_attractions_market'))

    op.drop_table('attractions')
    # ### end Alembic commands ###
